pack deps artifact to better support symbolic links

diff --git a/.github/workflows/build_orca.yml b/.github/workflows/build_orca.yml
--- a/.github/workflows/build_orca.yml
+++ b/.github/workflows/build_orca.yml
@@ -34,7 +34,19 @@ jobs:
         uses: actions/download-artifact@v7
         with:
           name: ${{ inputs.artifact-name }}
-          path: ${{ inputs.artifact-path }}
+          path: .
+
+      - name: Unpack dependencies
+        shell: bash
+        run: |
+          if [ ! -f deps_packet.tar ]; then
+            echo "Error: deps_packet.tar not found"
+            ls -R
+            exit 1
+          fi
+          mkdir -p ${{ inputs.artifact-path }}
+          tar -xf deps_packet.tar -C ${{ inputs.artifact-path }}
+          rm deps_packet.tar
 
       - uses: lukka/get-cmake@latest
         with:
